global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'empops-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['api:4005', 'host.docker.internal:4005']
        labels:
          environment: 'production'
          app: 'empops'
