export enum RoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  HR_MANAGER = 'HR_MANAGER',
  IT_MANAGER = 'IT_MANAGER',
  IT_TECHNICIAN = 'IT_TECHNICIAN',
  EMPLOYEE = 'EMPLOYEE',
  AUDITOR = 'AUDITOR',
}

export enum EmployeeStatus {
  PROBATION = 'PROBATION',
  CONFIRMED = 'CONFIRMED',
  NOTICE_PERIOD = 'NOTICE_PERIOD',
  RESIGNED = 'RESIGNED',
  TERMINATED = 'TERMINATED',
  RETIRED = 'RETIRED',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERN = 'INTERN',
}

export enum AttendanceMode {
  MOBILE_GPS = 'MOBILE_GPS',
  WEB_PORTAL = 'WEB_PORTAL',
  BIOMETRIC_DEVICE = 'BIOMETRIC_DEVICE',
  OFFICE_WIFI = 'OFFICE_WIFI',
  KIOSK_FACE = 'KIOSK_FACE',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  HALF_DAY = 'HALF_DAY',
  ON_LEAVE = 'ON_LEAVE',
  WEEK_OFF = 'WEEK_OFF',
  HOLIDAY = 'HOLIDAY',
}

export enum PunchType {
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
}

export enum LeaveTypeEnum {
  EARNED_LEAVE = 'EARNED_LEAVE',
  CASUAL_LEAVE = 'CASUAL_LEAVE',
  SICK_LEAVE = 'SICK_LEAVE',
  MATERNITY_LEAVE = 'MATERNITY_LEAVE',
  PATERNITY_LEAVE = 'PATERNITY_LEAVE',
  COMPENSATORY_OFF = 'COMPENSATORY_OFF',
  LOSS_OF_PAY = 'LOSS_OF_PAY',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum TicketCategoryEnum {
  HARDWARE = 'HARDWARE',
  SOFTWARE = 'SOFTWARE',
  ACCESS_REQUEST = 'ACCESS_REQUEST',
  NETWORK = 'NETWORK',
  HR_OPERATIONS = 'HR_OPERATIONS',
  WORKSTATION = 'WORKSTATION',
}

export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
}

export enum TicketStatus {
  NEW = 'NEW',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_USER = 'PENDING_USER',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum AssetCategoryEnum {
  LAPTOP = 'LAPTOP',
  DESKTOP = 'DESKTOP',
  MONITOR = 'MONITOR',
  MOBILE_DEVICE = 'MOBILE_DEVICE',
  TABLET = 'TABLET',
  NETWORK_EQUIPMENT = 'NETWORK_EQUIPMENT',
  SERVER = 'SERVER',
  PERIPHERAL = 'PERIPHERAL',
}

export enum AssetStatus {
  IN_STOCK = 'IN_STOCK',
  ASSIGNED = 'ASSIGNED',
  IN_REPAIR = 'IN_REPAIR',
  IN_TRANSIT = 'IN_TRANSIT',
  LOST = 'LOST',
  RETIRED = 'RETIRED',
  DISPOSED = 'DISPOSED',
}

export enum CustodyStatus {
  PENDING_ACKNOWLEDGEMENT = 'PENDING_ACKNOWLEDGEMENT',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  DISPUTED = 'DISPUTED',
  RETURNED = 'RETURNED',
}

export enum DepreciationMethod {
  STRAIGHT_LINE = 'STRAIGHT_LINE',
  WRITTEN_DOWN_VALUE = 'WRITTEN_DOWN_VALUE',
}

export enum ExitClearanceStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  ASSETS_PENDING = 'ASSETS_PENDING',
  CLEARED = 'CLEARED',
  REJECTED = 'REJECTED',
}
